baseURL: https://www.jonahramponi.com
languageCode: en-us
title: Jonah's ML Notes
theme: Archie
pygmentsstyle: "monokai"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
params:
	mode: "toggle" 
  math: true
  mathjax: true 
  katex: true 
paginate=3 # articles per page

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 3